baseURL = "https://blog.faboo.org/"
languageCode = "en-us"
theme = "hyde-hyde"
title = "Bert Radke"

## Site Settings
[params]
    author = "Bert Radke"
    description = "there is no silver bullet"
    authorimage = "img/bert_radke.png"
    dateformat = "2006-01-02"
    highlightjs = true
    highlightjsstyle = "darcula"
    postNavigation = false
    # please choose either GraphComment or Disqus
    #GraphCommentId = "..."

    # Table of contents
    #toc = none, "hugo", or "tocbot"

[privacy]
[privacy.youtube]
    privacyEnhanced = true

## Social Accounts
[params.social]
    github = "taseroth"
    xing = "Bert_Radke"
    linkedin = "bert-radke-3a533736"
    twitter = "taseroth"
    stackoverflow = "132270/bert"
    email = "bert.radke@pm.me"
#    keybase = "bertradke"

[permalinks]
  post = "/:year/:month/:slug/"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "post"
    url = "/post/"
#[[menu.main]]
#    name = "Portfolio"
#    identifier = "portfolio"
#    weight = 200
#    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
[[menu.main]]
    name = "Imprint"
    identifier = "imprint"
    weight = 999
    url = "/imprint/"
