[build]
publish = "public"
# Calls your package.json script: "build": "npm run hugo -- --gc --minify --cleanDestinationDir"
command = "npm run build"

[build.environment]
HUGO_VERSION = "0.150.0"
NODE_VERSION = "20"

# --- production ---
[context.production]
command = "npm run build -- --gc --minify --cleanDestinationDir"
[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# --- split1 (if you use it) ---
[context.split1]
command = "npm run build -- --gc --minify --cleanDestinationDir --enableGitInfo"
[context.split1.environment]
HUGO_VERSION = "0.150.0"
HUGO_ENV = "production"

# --- deploy previews ---
[context.deploy-preview]
command = "npm run build -- --gc --minify --cleanDestinationDir --buildFuture -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_VERSION = "0.150.0"

# --- branch deploys ---
[context.branch-deploy]
command = "npm run build -- --gc --minify --cleanDestinationDir -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
HUGO_VERSION = "0.150.0"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200
